[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
quilt_loom = "1.5.+"

minecraft = "1.20.4"
quilt_loader = "0.24.0"

parchment = "2024.02.25"
emi = "1.1.4+1.20.4"
modmenu = "9.0.0"
resourcefulconfig = "2.4.5"
lazydfu = "0.1.3"
sparkweave = "0.200.0"

universalgraves = "3.2.1+1.20.3"
sgui = "1.4.1+1.20.4"
placeholder-api = "2.3.0+1.20.3"
polymer = "0.7.7+1.20.4"
predicate-api = "0.3.0+1.20.2"
common-protection-api = "1.0.0"
server-translations-api = "2.2.0+1.20.3-rc1"
fabric-permissions-api = "0.2-SNAPSHOT"

trinkets = "3.8.1"

quilted_fabric_api = "9.0.0-alpha.5+0.96.11-1.20.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment_mappings = { module = "org.parchmentmc.data:parchment-1.20.4", version.ref = "parchment" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
sparkweave = { module = "dev.upcraft.sparkweave:Sparkweave-Quilt", version.ref = "sparkweave" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
resourcefulconfig_fabric = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.20.4", version.ref = "resourcefulconfig" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }

universalgraves = { module = "maven.modrinth:universal-graves", version.ref = "universalgraves" }
sgui = { module = "eu.pb4:sgui", version.ref = "sgui" }
placeholder-api = { module = "eu.pb4:placeholder-api", version.ref = "placeholder-api" }
polymer-core = { module = "eu.pb4:polymer-core", version.ref = "polymer" }
polymer-resource-pack = { module = "eu.pb4:polymer-resource-pack", version.ref = "polymer" }
polymer-virtual-entity = { module = "eu.pb4:polymer-virtual-entity", version.ref = "polymer" }
predicate-api = { module = "eu.pb4:predicate-api", version.ref = "predicate-api" }
common-protection-api = { module = "eu.pb4:common-protection-api", version.ref = "common-protection-api" }
server-translations-api = { module = "xyz.nucleoid:server-translations-api", version.ref = "server-translations-api" }
fabric-permissions-api = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-api" }

trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]
universalgraves_runtime = ["universalgraves", "sgui", "placeholder-api", "polymer-core", "polymer-resource-pack", "polymer-virtual-entity", "predicate-api", "common-protection-api", "server-translations-api", "fabric-permissions-api"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
